name: Validate meta data

on:
  pull_request:
    branches: [main]
    paths:
      - "meta.yaml"
  push:
    branches: [main]
    paths:
      - "meta.yaml"

permissions:
  contents: read

jobs:
  validate-meta-data:
    runs-on: ubuntu-latest
    name: Validate meta data file
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: mikefarah/yq@c14f446382944492701b16c1ddb48bb9dbe683e3 # v4.53.6
        with:
          cmd: yq -o=json '.' meta.yaml > meta.json
      - name: Validate meta data
        uses: cardinalby/schema-validator-action@95ce895b6846cc7d931785fcaa46c84816753612 # v3
        with:
          file: meta.json
          schema: meta.schema.json
